FROM base-images.mgti-dal-so-art.mrshmc.com/mmc/redhat/ubi8:latest
# First update the system to the latest levels - important this step is consistent across all RHEL7 Docker Images
RUN yum -y update  && yum clean all

# Add ZScaler certificate to relevant places to avoid SSL issues.
RUN echo "Installing ZScaler certificate" \
    && cp /usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt /etc/pki/ca-trust/source/anchors/ \
    && update-ca-trust 

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt

# Run the relevant commands to install any dependent packages and create any users/directories required. Always end with yum clean all to reduce size.
RUN echo 'INSTALLING NODE and dependencies' \
	&& curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - \
	&& yum -y install nodejs git krb5-devel wget make gcc-c++ sudo \
	&& npm install npm@6.14.13 -g \
	&& yum clean all \
	&& echo 'INSTALLING JQ' \
	&& wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/bin/jq \
	&& chmod +x /usr/bin/jq \
	&& yum clean all

# DO NOT COPY THIS TO PRODUCTION DOCKERFILE
# Adding root user to a docker image is usefull for dev purposes
# but is bad practice for production environment
RUN useradd --system node && echo "node:node" | chpasswd 
RUN usermod -aG wheel node 

COPY webapp/ /home/node/src

RUN echo 'INSTALLING NPM DEPENDENCIES' \
	&& echo "## Running git config --global url.https://.insteadOf git://" \
	&& git config --global url."https://".insteadOf git:// \
	&& echo "## Running npm install -g node-gyp" \
	&& npm install -g node-gyp \
	&& echo "## Running npm install -g bower" \
	&& npm install -g bower \
	&& echo "## Running npm install -g grunt-cli" \
	&& npm install -g grunt-cli \
	&& echo "## Running cd /home/node/src" \
	&& cd /home/node/src \
	&& echo "## Running npm install" \
	&& npm install \
	&& echo "## Running bower install --allow-root --force" \
	&& bower install --allow-root --force \
	&& echo "## Running chown -R node /home/node" \
	&& chown -R node /home/node 

# Install mongoexport for automated testing
# RUN echo $'[mongodb-org-3.2]\n\
# name=MongoDB Repository\n\
# baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/3.2/x86_64/\n\
# gpgcheck=1\n\
# enabled=1\n\
# gpgkey=https://www.mongodb.org/static/pgp/server-3.2.asc' > /etc/yum.repos.d/mongodb-org.repo

# RUN yum -y install mongodb-org-tools

USER node
WORKDIR /home/node/src

# Install ldjson-stream for testing
RUN npm install ldjson-stream

CMD npm run featureTest
