FROM base-images.mgti-dal-so-art.mrshmc.com/mmc/redhat/ubi8:latest
# First update the system to the latest levels - important this step is consistent across all RHEL7 Docker Images
RUN yum -y update  && yum clean all

# Add ZScaler certificate to relevant places to avoid SSL issues.
RUN echo "Installing ZScaler certificate" \
    && cp /usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt /etc/pki/ca-trust/source/anchors/ \
    && update-ca-trust 

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt

# DO NOT COPY THIS TO PRODUCTION DOCKERFILE
# Adding root user to a docker image is usefull for dev purposes
# but is bad practice for production environment
RUN useradd --system node && echo "node:node" | chpasswd 
RUN usermod -aG wheel node 

# Run the relevant commands to install any dependent packages and create any users/directories required. Always end with yum clean all to reduce size.
RUN echo 'INSTALLING NODE and dependencies' \
    && curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - \
    && yum -y install nodejs git krb5-devel wget sudo nano \
    && npm install npm@6.14.13 -g \
    && yum clean all \
    && echo 'INSTALLING JQ' \
    && wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/bin/jq \
    && chmod +x /usr/bin/jq \
    && yum clean all

COPY article-importer/package.json article-importer/package-lock.json /home/node/src/
WORKDIR /home/node/src

RUN echo 'INSTALLING APPLICATION AND ITS DEPENDENCIES' \
    && npm install -g node-gyp \
    && npm install -g bower \
    && npm install -g grunt-cli \
    && npm install \
    && npm uninstall -g node-gyp \
    && npm uninstall -g bower \
    && npm uninstall -g grunt-cli 

# Copy and install the application
COPY article-importer/ /home/node/src

# Set up user and user permissions
RUN chown -R node:node .
USER node

EXPOSE 9003

CMD node app.js