FROM ubuntu
# First update the system to the latest levels - important this step is consistent across all RHEL7 Docker Images
COPY article-importer/package.json article-importer/package-lock.json /home/node/src/
WORKDIR /home/node/src

# Set up user and user permissions
RUN chown -R node:node .

EXPOSE 9002

CMD node app.js
