FROM base-images.mgti-dal-so-art.mrshmc.com/mmc/redhat/ubi8:latest
# First update the system to the latest levels - important this step is consistent across all RHEL7 Docker Images
RUN yum -y update  && yum clean all

# Add ZScaler certificate to relevant places to avoid SSL issues.
RUN echo "Installing ZScaler certificate" \
    && cp /usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt /etc/pki/ca-trust/source/anchors/ \
    && update-ca-trust 

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.com/ZscalerRootCertificate-2048-SHA256.crt

# Run the relevant commands to install any dependent packages and create any users/directories required. Always end with yum clean all to reduce size.
RUN echo 'INSTALLING NODE and dependencies' \
    && curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - \
    && yum -y install nodejs git krb5-devel wget make gcc-c++ nano \
    && npm install npm@6.14.13 -g \
    && yum clean all

# Add a non-root user
RUN useradd --system node

# Copy over package lists and install them
COPY data-importer/package.json data-importer/package-lock.json /home/node/src/

RUN echo 'INSTALLING PACKAGE DEPENDENCIES' \
    && git config --global url."https://".insteadOf git:// \
    && cd /home/node/src \
    && npm install 

# Set the working directory, expose port and set a default user
RUN mkdir -p /data_files
RUN chown node:node /data_files

# Copy over the rest of the application
COPY data-importer/ /home/node/src/

USER node
WORKDIR /home/node/src

ENV INCOMING_FOLDER /data_files
ENV PROCESSING_FOLDER  /tmp
ENV DATA_FOLDER /tmp

EXPOSE 9004

CMD node index.js
