name: Webapp Build and Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      version:
        description: Version (leave blank to build new version)

jobs:
  all-here:
    uses: ./.github/workflows/build-and-deploy-template.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      dockerfile: deployments/docker/Dockerfile-webapp
      image_name: marshmarketplace-webapp
      deployments:  '{"include":["webapp"]}'